language: python

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - rosetta/setup
  - rosetta/build
  - rosetta/run

script: rosetta/test
