version: '3'
services:

  slurmclustermaster-main:
    image: "rosetta/slurmclustermaster"
    container_name: slurmclustermaster-main
    hostname: slurmclustermaster-main
    environment:
      - SAFEMODE=False
    privileged: true
    volumes:
      - ./data_rosetta/shared:/shared
      # - ./data/singularity_cache:/rosetta/.singularity/cache # Not working, check permissions...

  slurmclusterworker-one:
    image: "rosetta/slurmclusterworker"
    container_name: slurmclusterworker-one
    hostname: slurmclusterworker-one
    environment:
      - SAFEMODE=False
    privileged: true
    volumes:
      - ./data_rosetta/shared:/shared

  dregistry:
    container_name: dregistry
    hostname: dregistry
    image: "rosetta/dregistry"
    volumes:
      - ./data_rosetta/dregistry:/var/lib/registry
    ports:
      - "5000:5000"

  postgres:
    image: "rosetta/postgres"
    container_name: postgres
    hostname: postgres
    environment:
      - SAFEMODE=False
    volumes:
      - ./data_rosetta/postgres/data:/data    

  webapp:
    image: "rosetta/webapp"
    container_name: webapp
    hostname: webapp
    environment:
      - SAFEMODE=False
      - DJANGO_DEBUG=True
      - DJANGO_LOG_LEVEL=CRITICAL
      - ROSETTA_LOG_LEVEL=DEBUG
      #- ROSETTA_TUNNEL_HOST=
      #- ROSETTA_WEBAPP_HOST=
      #- ROSETTA_WEBAPP_PORT=8080
      #- LOCAL_DOCKER_REGISTRY_HOST=
      #- LOCAL_DOCKER_REGISTRY_PORT=5000
      #- DJANGO_EMAIL_APIKEY=""
      #- DJANGO_EMAIL_FROM="Rosetta Platform <notifications@rosetta.platform>"
      #- DJANGO_PUBLIC_HTTP_HOST=http://localhost:8080
      #- DJANGO_SECRET_KEY=""
    ports:
      - "8080:8080"
      - "7000-7020:7000-7020"
    volumes:
      - ./data_rosetta/webapp/data:/data
      - ./data_rosetta/webapp/log:/var/log/webapp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/webapp/code:/opt/code

  proxy:
    image: "rosetta/proxy"
    container_name: proxy
    hostname: proxy
    environment:
      - SAFEMODE=False
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data_rosetta/proxy/data:/data    








