# Generated by Django 2.2.1 on 2021-01-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='protocol',
            field=models.CharField(blank=True, default='http', max_length=36, null=True, verbose_name='Container protocol'),
        ),
    ]
